name: Deploy Docs

on:
  push:
    branches-ignore:
      - 'dependabot**'

jobs:
  deploy-docs:
    if: github.repository == 'joinfaces/joinfaces'
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_joinfacesDocsUser: ${{ secrets.JOINFACES_DOCS_USER }}
      ORG_GRADLE_PROJECT_joinfacesDocsPass: ${{ secrets.JOINFACES_DOCS_PASS }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2.0.2

      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew -V uploadDocs -s

      - run: ./gradlew -V publish
        if: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
